# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.PositiveIntegerField(default=0)),
                ('bank_money', models.PositiveIntegerField(default=0)),
                ('pocket_money', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='players_stock_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField(blank=True)),
                ('stock_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='players_stock_list',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopolydatabase.stock'),
        ),
        migrations.AddField(
            model_name='player',
            name='owned_stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monopolydatabase.players_stock_list'),
        ),
    ]
