# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='poisoned',
            field=models.BooleanField(default=False),
        ),
    ]
