# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0002_player_poisoned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
