# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0003_auto_20170718_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owned_stock',
        ),
        migrations.AddField(
            model_name='player',
            name='owned_stock',
            field=models.ManyToManyField(to='monopolydatabase.players_stock_list'),
        ),
    ]
