# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0004_auto_20170718_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='players_stock_list',
            name='owned_player',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
