# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0005_players_stock_list_owned_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owned_stock',
        ),
        migrations.AlterField(
            model_name='players_stock_list',
            name='owned_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopolydatabase.player'),
        ),
    ]
