# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0006_auto_20170718_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(blank=True, max_length=100)),
                ('land_type', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('houses', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopolydatabase.player')),
            ],
        ),
    ]
