# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0011_auto_20170731_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_random_risefall_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risefall', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='random_risefall_list',
        ),
        migrations.AddField(
            model_name='stock_random_risefall_list',
            name='stockname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopolydatabase.stock'),
        ),
    ]
