# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolydatabase', '0012_auto_20170731_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='mansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
